// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CDataFormatDisp wrapper class

class CDataFormatDisp : public COleDispatchDriver
{
public:
	CDataFormatDisp() {}		// Calls COleDispatchDriver default constructor
	CDataFormatDisp(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CDataFormatDisp(const CDataFormatDisp& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
};
