//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Equipment.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_EQUIPMENT_DIALOG            103
#define IDS_EQUIPKIND                   102
#define IDI_TOOLBAR2                    103
#define IDI_TOOLBAR1                    102
#define IDS_ADDMODE                     103
#define IDI_TOOLBAR3                    104
#define IDS_REDUSEMODE                  104
#define IDI_TOOLBAR4                    105
#define IDS_USESTATE                    105
#define IDI_TOOLBAR5                    106
#define IDS_ADDEQUIP                    106
#define IDI_TOOLBAR6                    107
#define IDS_UPDATEEQUIP                 107
#define IDI_TOOLBAR7                    108
#define IDS_DELETEEQUIP                 108
#define IDI_TOOLBAR8                    109
#define IDS_REDUSEEQUIP                 109
#define IDI_TOOLBAR9                    110
#define IDS_DEPRECIATION                110
#define IDS_CANCELDEPRE                 111
#define IDI_TOOLBAR10                   111
#define IDI_TOOLBAR11                   112
#define IDS_BACKUP                      112
#define IDI_TOOLBAR12                   113
#define IDS_Restore                     113
#define IDI_TOOLBAR13                   114
#define IDS_QUIT                        114
#define IDD_EQUIPKIND_DIALOG            115
#define IDD_ADDKINDS_DIALOG             116
#define IDD_REDUCEKINDS_DIALOG          117
#define IDD_USESTATE_DIALOG             118
#define IDD_ADDEQUIP_DIALOG             119
#define IDD_UPDATEEQUIP_DIALOG          120
#define IDD_DELETEEQUIP_DIALOG          121
#define IDD_DELETEEQUIPMENT_DIALOG      124
#define IDD_REDUCEEQUIP_DIALOG          125
#define IDD_DEPRE_DIALOG                126
#define IDD_UNDEPRE_DIALOG              127
#define IDR_MAINFRAME                   128
#define IDD_DATABACKUP_DIALOG           129
#define IDD_DATARESTORE_DIALOG          130
#define IDR_MAINTITLE                   131
#define IDR_MAINMENU                    132
#define IDD_SYSINI_DIALOG               133
#define IDB_TOOLBARBIP                  135
#define IDR_TOOLBAR1                    137
#define IDB_BITMAP1                     139
#define IDB_BITMAP2                     141
#define IDB_BITMAP3                     154
#define IDR_TOOLBAR2                    173
#define IDI_ICON1                       188
#define IDI_ICON2                       189
#define IDI_ICON3                       190
#define IDI_ICON4                       191
#define IDI_ICON5                       192
#define IDI_ICON6                       197
#define IDB_ABOUTBITMAP                 199
#define ID_BUTTONADD                    201
#define ID_BUTTONUPDATE                 202
#define ID_BUTTONDELETE                 203
#define ID_BUTTONREFRESH                204
#define ID_BUTTONCLOSE                  205
#define IDS_Depremanage                 206
#define IDS_redusemange                 207
#define IDS_Undepre                     208
#define IDS_Sysini                      209
#define IDC_mainpicture                 1001
#define ID_toolbar                      1004
#define ID_statusbar                    1005
#define IDC_EDIT1                       1005
#define IDC_Add                         1006
#define IDC_SOURCEVALUE                 1006
#define IDC_UPDATE                      1007
#define IDC_ADDUPDEPRE                  1007
#define IDC_DELETE                      1008
#define IDC_PUREVALUE                   1008
#define IDC_REFRESH                     1009
#define IDC_SPEC                        1009
#define IDC_QUIT                        1010
#define IDC_PREPURSERATE                1010
#define IDC_PREPUREVALUE                1011
#define IDC_PREUSEMONTH                 1012
#define IDC_DEPREMONTH                  1013
#define IDC_MONTHDEPRERATE              1015
#define IDC_MONTHDEPREVALUE             1016
#define IDC_YEARSOURCEVALUE             1017
#define IDC_YEARESOURCEADD              1018
#define IDC_YEARESOURCEDECREAWE         1019
#define IDC_PERIODVALUE                 1020
#define IDC_YEAREDEPRE                  1021
#define IDC_YEAREDEPREADD               1022
#define IDC_DATAGRID                    1023
#define IDC_YEARDEPREDECREASE           1023
#define IDC_PERIODDEPRE                 1024
#define IDC_LIST                        1025
#define IDC_EQUIPKINDS                  1028
#define IDC_USESTATE                    1029
#define IDC_ADDKINDS                    1030
#define IDC_REGDATE                     1031
#define IDC_EQUIPNAME                   1032
#define IDC_DEPREMETHOD                 1033
#define IDC_QUERYCONDITION              1034
#define IDC_QUERY                       1035
#define IDC_LIST1                       1036
#define IDC_EquipID                     1037
#define IDC_REDUCEMODE                  1037
#define IDC_ID                          1039
#define IDC_NAME                        1040
#define IDC_CLERAERNING                 1041
#define IDC_CLEARECHARGE                1042
#define IDC_CLEARDATE                   1043
#define IDC_CLEARREASON                 1044
#define IDC_DATETIMEPICKER1             1044
#define IDC_RICHEDIT2                   1046
#define IDC_BUTTON1                     1047
#define IDC_ADODC2                      1051
#define IDS_COMPANY                     1202
#define ID_MENUKIND                     32771
#define ID_MENUADDMODE                  32772
#define ID_MENUREDUSEMODE               32773
#define ID_MENUUSEMODE                  32774
#define ID_MENUADDEQUIP                 32775
#define ID_MENUUPDATEEQUIP              32776
#define ID_MENUDELETEEQUIP              32777
#define ID_MENUREDUSEEQUIP              32778
#define ID_MENUDEPRECIATION             32780
#define ID_MENUCANCELPRECE              32781
#define ID_MENUBACKUP                   32782
#define ID_MENURESTORE                  32783
#define ID_MENUSYSINI                   32784
#define ID_MENUITEM32785                32785
#define ID_NOTE                         32785
#define ID_MENUITEM32786                32786
#define ID_Calculator                   32786
#define ID_MENUABOUT                    32787
#define ID_BUTTON32788                  32788

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        228
#define _APS_NEXT_COMMAND_VALUE         32800
#define _APS_NEXT_CONTROL_VALUE         1052
#define _APS_NEXT_SYMED_VALUE           134
#endif
#endif
